title: Linee Guida ATI Project
description: "Documentazione e linee guida per ATI Project"
baseurl: "/webjekyll"
url: "https://giacomomarani.github.io"

# Build settings
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-archives

# Paginate settings
paginate: 5
paginate_path: "/page:num/"

# Archives settings
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: archive
  permalinks:
    year: /:year/
    month: /:year/:month/
    day: /:year/:month/:day/
    tag: /tag/:name/
    category: /category/:name/

# Other settings
author:
  name: "Giacomo Marani"
