title: Linee Guida ATI Project
description: "Documentazione e linee guida per ATI Project"
baseurl: "/webjekyll" # Sostituisci con il nome del tuo repository
url: "https://giacomomarani.github.io"

# Build settings
theme: minima
plugins:
  - jekyll-feed
